/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mia' at '16. 9. 21 오전 10:24' with Gradle 2.14.1
 *
 * @author mia, @date 16. 9. 21 오전 10:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
